name: Run unit tests and linter
on:
  push:
jobs:
  Run-unit-tests-and-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Composer install
        run: composer install

      - name: Run linter
        run: make lint

      - name: Run test & publish code coverage
        uses: paambaati/codeclimate-action@v5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          coverageLocations: build/logs/clover.xml:clover
          debug: true
