name: Run unit tests and linter
on:
  push:
  pull_request:
jobs:
  Run-unit-tests-and-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Run unit tests
        run: make test

      - name: Run linter
        run: make lint
